apiVersion : apps/v1
kind: Deployment
metadata:
  name: "itequiaaks-5261"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "itequiaaks-5261"
  template:
    metadata:
      labels:
        app: "itequiaaks-5261"
    spec:
      containers:
        - name: "itequiaaks-5261"
          image: "itequiadev.azurecr.io/itequiaaks"
          ports:
          - containerPort: 8080